# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "merchant-1-test.xcodeproj")
    build_app(scheme: "merchant-1-test")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

  

  desc "To build our app"
  lane :build_app do
    gym(
      project: "merchant-1-test.xcodeproj",
      scheme: "merchant-1-test",
      clean: true,
      export_method: "app-store",
      export_options: {provisioningProfiles: {"com.springbig.merchant-1-test" => "merchant-1-test"}},
      export_xcargs: "-allowProvisioningUpdates",
      output_name: "M1.ipa"
    )
  end

  desc "To deliver the app to store"
  lane :upload_to_app_store do
    deliver(
      ipa: "M1.ipa",
      skip_screenshots: true,
      skip_metadata: true,
      skip_app_version_update: true,
      force: true
    )
  end

  desc "certs and profiles"
  lane :beta do
    match(type: 'appstore')
  end
end
